https://keras.io/api/layers/regularizers/

In [1]:
from tensorflow.keras import layers

In [2]:
from tensorflow.keras import regularizers

In [3]:
import tensorflow as tf

In [4]:
layer = layers.Dense(
    units = 1,
    kernel_initializer='ones',
    kernel_regularizer=regularizers.L2(1),
    #kernel_regularizer=regularizers.L1L2(l1=1e-5, l2=1e-4),
    #bias_regularizer=regularizers.L2(100),
    #activity_regularizer=regularizers.L2(1e-5),
    )

In [5]:
layer = layers.Dense(
    units = 1,
    kernel_initializer='ones',
    kernel_regularizer=regularizers.OrthogonalRegularizer(
        factor = 0.01),
    #kernel_regularizer=regularizers.L1L2(l1=1e-5, l2=1e-4),
    #bias_regularizer=regularizers.L2(100),
    #activity_regularizer=regularizers.L2(1e-5),
    )

In [6]:
import numpy as np

In [7]:
x = tf.ones(shape = (1, 2))

In [8]:
y = layer(x)

In [9]:
layer.losses

[<tf.Tensor: shape=(), dtype=float32, numpy=0.01>]

In [10]:
x

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 1.]], dtype=float32)>

In [11]:
tf.math.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [13]:
from tensorflow.math import *

In [19]:
x = np.array([[1,2]])

In [20]:
tf.square(x)

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 4]])>

In [21]:
tf.reduce_sum(tf.square(x))

<tf.Tensor: shape=(), dtype=int32, numpy=5>